service: adapcall-api

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  stage: dev
  environment:
    region: sa-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
 exclude:
  - node_modules/aws-sdk/**

functions:
  listLigacoes:
    handler: src/v1/ligacoes/list.run
    events:
      - http:
          path: v1/ligacoes
          method: get

resources:
  Resources:
    tableLigacoes:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Ligacoes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      domain:
        sources:
          - table: Ligacoes
            sources: [./data/Ligacoes-inicial.json]