service: adapcall-api

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  stage: dev
  memory: 128
  environment:
    region: sa-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: 
        Fn::Join:
          - ""
          - - "arn:aws:dynamodb:::"
            - "Ref" : "Adapcall."
            - "*"

# you can add packaging information here
package:
 exclude:
  - node_modules/aws-sdk/**

functions:
  listLigacoes:
    handler: src/v1/ligacoes/list.run
    events:
      - http:
          path: v1/ligacoes
          method: get
  createLigacoes:
    handler: src/v1/ligacoes/create.run
    events:
      - http:
          path: v1/ligacoes
          method: post

resources:
  Resources:
    tableLigacoes:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Adapcall.Ligacoes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      domain:
        sources:
          - table: Adapcall.Ligacoes
            sources: [./data/Ligacoes-inicial.json]